import Head from "next/head";
import AllCollections from "../components/allCollections/AllCollections";
import HeroComponent from "../components/hero/HeroComponent";
import NewsLetter from "../components/newsLetter/NewsLetter";
import Testimonials from "../components/testimonials/Testimonials";
import TrendyCollections from "../components/trendy/TrendyCollections";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HeroComponent />
      <TrendyCollections />
      <AllCollections />
      <Testimonials />
      <NewsLetter />
    </div>
  );
}
